import type { NextPage } from "next";
import Head from "next/head";
import Header from "./components/Header";
import ItemCard from "./components/ItemCard";

const Home: NextPage = () => {
  return (
    <div className="flex flex-col items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="mt-10 flex w-4/5 flex-row items-center justify-center">
        <ItemCard />
        <ItemCard />
        <ItemCard />
      </div>
    </div>
  );
};

export default Home;
